name: "Dev Build"

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  Prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci
        
  Lint:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

  Build:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
